### ISSUE TITLE
make cross-all all failed

### ISSUE THREAD

**Issue by MS-7160** [anshulrouthu/RPiCast#3] opened 2016-08-13 04:19 UTC
make failed

man1@man1-S7211:~/rpicast$ make cross-all all
make[1]: Entering directory '/home/man1/rpicast'
[CXX] source/porting_layers/components/video_capture.o
[CXX] source/porting_layers/components/video_tunnel.o
[CXX] source/porting_layers/components/demux.o
[CXX] source/porting_layers/components/file_io.o
[CXX] source/porting_layers/components/video_encoder.o
[CXX] source/framework/timer.o
[CXX] source/framework/utils.o
[CXX] source/framework/socket_io.o
[CXX] source/framework/worker.o
[CXX] source/framework/ssdpdiscovery.o
[CXX] source/framework/basepipe.o
[CXX] source/framework/mutex.o
[CXX] source/framework/buffer.o
[CXX] source/osapi/osapi_linux.o
[CXX] source/porting_layers/av_pipe/avframe_buffer.o
[CXX] source/porting_layers/av_pipe/av_pipe.o
Linking... rpi-build/librpicast-server.so
[CXX] source/main/rpicast-server.o
Linking... rpi-build/rpicast-server
# @scp -r rpi-build/\* root@192.168.1.2:workspace/

make[1]: Leaving directory '/home/man1/rpicast'
[CXX] source/porting_layers/components/video_capture.o
[CXX] source/porting_layers/components/demux.o
In file included from source/porting_layers/components/demux.h:27:0,
                 from source/porting_layers/components/demux.cpp:24:
source/porting_layers/components/demux.cpp: In member function ‘virtual VC_STATUS DemuxDevice::Initialize()’:
source/porting_layers/components/demux.cpp:46:94: error: cast from ‘AVBitStreamFilterContext_’ to ‘int’ loses precision [-fpermissive]
 ter_ctx,, "Error(%d): Unable to create H264 bit stream filter", (int)m_h264filte
                                                                      ^
./source/framework/utils.h:85:55: note: in definition of macro ‘DBGPRINT’
 #define DBGPRINT(level,msg) vcDebug(level).DebugPrint msg
                                                       ^
./source/framework/utils.h:110:35: note: in expansion of macro ‘DBG_DBG_ERR’
 #define DBG_ERR(format, args...)  DBG_DBG_ERR(LEVEL_ERROR,  format, ##args)
                                   ^
./source/framework/utils.h:120:9: note: in expansion of macro ‘DBG_ERR’
         DBG_ERR("("#condition") "msg,##args);             \
         ^
source/porting_layers/components/demux.cpp:46:5: note: in expansion of macro ‘DBG_CHECK’
     DBG_CHECK(!m_h264filter_ctx,, "Error(%d): Unable to create H264 bit stream f
     ^
Makefile:89: recipe for target 'source/porting_layers/components/demux.o' failed
make: *_\* [source/porting_layers/components/demux.o] Error 1
man1@man1-S7211:~/rpicast$ 

Why?

**Comment by anshulrouthu** [comment] 2016-08-17 15:11
I think those errors are caused by improper type casting, can easily be fixed. on 64 bit machine pointer is 64 bit wide and int is 32 bits, casting from a 64 bit type to a 32 bit type looses data and is not good. I started this project on a 32 bit machine hence got away without causing any error here. Feel free to make changes and do a pull request.

**Comment by anshulrouthu** [comment] 2017-12-01 18:44
Fixed with the latest commit

**Closed as completed by anshulrouthu** 2017-12-01 18:44 UTC
